spring.application.name=congestion

spring.datasource.url=jdbc:postgresql://localhost:5432/webpro
spring.datasource.username=postgres
spring.datasource.password=dksl@5421

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080